<?php

/**
 * Base class that represents a row from the 'app_blogs_entries' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 07/08/11 10:10:12
 *
 * @package    lib.model.om
 */
abstract class BaseAppBlogsEntries extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        AppBlogsEntriesPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the page_id field.
	 * @var        int
	 */
	protected $page_id;

	/**
	 * The value for the lang field.
	 * @var        string
	 */
	protected $lang;

	/**
	 * The value for the title field.
	 * @var        string
	 */
	protected $title;

	/**
	 * The value for the subtitle1 field.
	 * @var        string
	 */
	protected $subtitle1;

	/**
	 * The value for the subtitle2 field.
	 * @var        string
	 */
	protected $subtitle2;

	/**
	 * The value for the body field.
	 * @var        string
	 */
	protected $body;

	/**
	 * The value for the date field.
	 * @var        string
	 */
	protected $date;

	/**
	 * The value for the tags field.
	 * @var        string
	 */
	protected $tags;

	/**
	 * The value for the url field.
	 * @var        string
	 */
	protected $url;

	/**
	 * The value for the site_id field.
	 * @var        int
	 */
	protected $site_id;

	/**
	 * The value for the actiu field.
	 * Note: this column has a database default value of: 1
	 * @var        int
	 */
	protected $actiu;

	/**
	 * @var        AppBlogsPages
	 */
	protected $aAppBlogsPages;

	/**
	 * @var        array AppBlogMultimediaEntries[] Collection to store aggregation of AppBlogMultimediaEntries objects.
	 */
	protected $collAppBlogMultimediaEntriess;

	/**
	 * @var        Criteria The criteria used to select the current contents of collAppBlogMultimediaEntriess.
	 */
	private $lastAppBlogMultimediaEntriesCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'AppBlogsEntriesPeer';

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->actiu = 1;
	}

	/**
	 * Initializes internal state of BaseAppBlogsEntries object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [page_id] column value.
	 * 
	 * @return     int
	 */
	public function getPageId()
	{
		return $this->page_id;
	}

	/**
	 * Get the [lang] column value.
	 * 
	 * @return     string
	 */
	public function getLang()
	{
		return $this->lang;
	}

	/**
	 * Get the [title] column value.
	 * 
	 * @return     string
	 */
	public function getTitle()
	{
		return $this->title;
	}

	/**
	 * Get the [subtitle1] column value.
	 * 
	 * @return     string
	 */
	public function getSubtitle1()
	{
		return $this->subtitle1;
	}

	/**
	 * Get the [subtitle2] column value.
	 * 
	 * @return     string
	 */
	public function getSubtitle2()
	{
		return $this->subtitle2;
	}

	/**
	 * Get the [body] column value.
	 * 
	 * @return     string
	 */
	public function getBody()
	{
		return $this->body;
	}

	/**
	 * Get the [optionally formatted] temporal [date] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getDate($format = 'Y-m-d H:i:s')
	{
		if ($this->date === null) {
			return null;
		}


		if ($this->date === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->date);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->date, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [tags] column value.
	 * 
	 * @return     string
	 */
	public function getTags()
	{
		return $this->tags;
	}

	/**
	 * Get the [url] column value.
	 * 
	 * @return     string
	 */
	public function getUrl()
	{
		return $this->url;
	}

	/**
	 * Get the [site_id] column value.
	 * 
	 * @return     int
	 */
	public function getSiteId()
	{
		return $this->site_id;
	}

	/**
	 * Get the [actiu] column value.
	 * 
	 * @return     int
	 */
	public function getActiu()
	{
		return $this->actiu;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     AppBlogsEntries The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = AppBlogsEntriesPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [page_id] column.
	 * 
	 * @param      int $v new value
	 * @return     AppBlogsEntries The current object (for fluent API support)
	 */
	public function setPageId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->page_id !== $v) {
			$this->page_id = $v;
			$this->modifiedColumns[] = AppBlogsEntriesPeer::PAGE_ID;
		}

		if ($this->aAppBlogsPages !== null && $this->aAppBlogsPages->getId() !== $v) {
			$this->aAppBlogsPages = null;
		}

		return $this;
	} // setPageId()

	/**
	 * Set the value of [lang] column.
	 * 
	 * @param      string $v new value
	 * @return     AppBlogsEntries The current object (for fluent API support)
	 */
	public function setLang($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->lang !== $v) {
			$this->lang = $v;
			$this->modifiedColumns[] = AppBlogsEntriesPeer::LANG;
		}

		return $this;
	} // setLang()

	/**
	 * Set the value of [title] column.
	 * 
	 * @param      string $v new value
	 * @return     AppBlogsEntries The current object (for fluent API support)
	 */
	public function setTitle($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->title !== $v) {
			$this->title = $v;
			$this->modifiedColumns[] = AppBlogsEntriesPeer::TITLE;
		}

		return $this;
	} // setTitle()

	/**
	 * Set the value of [subtitle1] column.
	 * 
	 * @param      string $v new value
	 * @return     AppBlogsEntries The current object (for fluent API support)
	 */
	public function setSubtitle1($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->subtitle1 !== $v) {
			$this->subtitle1 = $v;
			$this->modifiedColumns[] = AppBlogsEntriesPeer::SUBTITLE1;
		}

		return $this;
	} // setSubtitle1()

	/**
	 * Set the value of [subtitle2] column.
	 * 
	 * @param      string $v new value
	 * @return     AppBlogsEntries The current object (for fluent API support)
	 */
	public function setSubtitle2($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->subtitle2 !== $v) {
			$this->subtitle2 = $v;
			$this->modifiedColumns[] = AppBlogsEntriesPeer::SUBTITLE2;
		}

		return $this;
	} // setSubtitle2()

	/**
	 * Set the value of [body] column.
	 * 
	 * @param      string $v new value
	 * @return     AppBlogsEntries The current object (for fluent API support)
	 */
	public function setBody($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->body !== $v) {
			$this->body = $v;
			$this->modifiedColumns[] = AppBlogsEntriesPeer::BODY;
		}

		return $this;
	} // setBody()

	/**
	 * Sets the value of [date] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     AppBlogsEntries The current object (for fluent API support)
	 */
	public function setDate($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->date !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->date !== null && $tmpDt = new DateTime($this->date)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->date = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = AppBlogsEntriesPeer::DATE;
			}
		} // if either are not null

		return $this;
	} // setDate()

	/**
	 * Set the value of [tags] column.
	 * 
	 * @param      string $v new value
	 * @return     AppBlogsEntries The current object (for fluent API support)
	 */
	public function setTags($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->tags !== $v) {
			$this->tags = $v;
			$this->modifiedColumns[] = AppBlogsEntriesPeer::TAGS;
		}

		return $this;
	} // setTags()

	/**
	 * Set the value of [url] column.
	 * 
	 * @param      string $v new value
	 * @return     AppBlogsEntries The current object (for fluent API support)
	 */
	public function setUrl($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->url !== $v) {
			$this->url = $v;
			$this->modifiedColumns[] = AppBlogsEntriesPeer::URL;
		}

		return $this;
	} // setUrl()

	/**
	 * Set the value of [site_id] column.
	 * 
	 * @param      int $v new value
	 * @return     AppBlogsEntries The current object (for fluent API support)
	 */
	public function setSiteId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->site_id !== $v) {
			$this->site_id = $v;
			$this->modifiedColumns[] = AppBlogsEntriesPeer::SITE_ID;
		}

		return $this;
	} // setSiteId()

	/**
	 * Set the value of [actiu] column.
	 * 
	 * @param      int $v new value
	 * @return     AppBlogsEntries The current object (for fluent API support)
	 */
	public function setActiu($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->actiu !== $v || $this->isNew()) {
			$this->actiu = $v;
			$this->modifiedColumns[] = AppBlogsEntriesPeer::ACTIU;
		}

		return $this;
	} // setActiu()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			if ($this->actiu !== 1) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->page_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->lang = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->title = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->subtitle1 = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->subtitle2 = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->body = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->date = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->tags = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->url = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->site_id = ($row[$startcol + 10] !== null) ? (int) $row[$startcol + 10] : null;
			$this->actiu = ($row[$startcol + 11] !== null) ? (int) $row[$startcol + 11] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 12; // 12 = AppBlogsEntriesPeer::NUM_COLUMNS - AppBlogsEntriesPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating AppBlogsEntries object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aAppBlogsPages !== null && $this->page_id !== $this->aAppBlogsPages->getId()) {
			$this->aAppBlogsPages = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AppBlogsEntriesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = AppBlogsEntriesPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aAppBlogsPages = null;
			$this->collAppBlogMultimediaEntriess = null;
			$this->lastAppBlogMultimediaEntriesCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AppBlogsEntriesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseAppBlogsEntries:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				AppBlogsEntriesPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseAppBlogsEntries:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AppBlogsEntriesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseAppBlogsEntries:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseAppBlogsEntries:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				AppBlogsEntriesPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aAppBlogsPages !== null) {
				if ($this->aAppBlogsPages->isModified() || $this->aAppBlogsPages->isNew()) {
					$affectedRows += $this->aAppBlogsPages->save($con);
				}
				$this->setAppBlogsPages($this->aAppBlogsPages);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = AppBlogsEntriesPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = AppBlogsEntriesPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += AppBlogsEntriesPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collAppBlogMultimediaEntriess !== null) {
				foreach ($this->collAppBlogMultimediaEntriess as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aAppBlogsPages !== null) {
				if (!$this->aAppBlogsPages->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aAppBlogsPages->getValidationFailures());
				}
			}


			if (($retval = AppBlogsEntriesPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collAppBlogMultimediaEntriess !== null) {
					foreach ($this->collAppBlogMultimediaEntriess as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = AppBlogsEntriesPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getPageId();
				break;
			case 2:
				return $this->getLang();
				break;
			case 3:
				return $this->getTitle();
				break;
			case 4:
				return $this->getSubtitle1();
				break;
			case 5:
				return $this->getSubtitle2();
				break;
			case 6:
				return $this->getBody();
				break;
			case 7:
				return $this->getDate();
				break;
			case 8:
				return $this->getTags();
				break;
			case 9:
				return $this->getUrl();
				break;
			case 10:
				return $this->getSiteId();
				break;
			case 11:
				return $this->getActiu();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = AppBlogsEntriesPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getPageId(),
			$keys[2] => $this->getLang(),
			$keys[3] => $this->getTitle(),
			$keys[4] => $this->getSubtitle1(),
			$keys[5] => $this->getSubtitle2(),
			$keys[6] => $this->getBody(),
			$keys[7] => $this->getDate(),
			$keys[8] => $this->getTags(),
			$keys[9] => $this->getUrl(),
			$keys[10] => $this->getSiteId(),
			$keys[11] => $this->getActiu(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = AppBlogsEntriesPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setPageId($value);
				break;
			case 2:
				$this->setLang($value);
				break;
			case 3:
				$this->setTitle($value);
				break;
			case 4:
				$this->setSubtitle1($value);
				break;
			case 5:
				$this->setSubtitle2($value);
				break;
			case 6:
				$this->setBody($value);
				break;
			case 7:
				$this->setDate($value);
				break;
			case 8:
				$this->setTags($value);
				break;
			case 9:
				$this->setUrl($value);
				break;
			case 10:
				$this->setSiteId($value);
				break;
			case 11:
				$this->setActiu($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = AppBlogsEntriesPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setPageId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setLang($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setTitle($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setSubtitle1($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setSubtitle2($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setBody($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setDate($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setTags($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setUrl($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setSiteId($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setActiu($arr[$keys[11]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(AppBlogsEntriesPeer::DATABASE_NAME);

		if ($this->isColumnModified(AppBlogsEntriesPeer::ID)) $criteria->add(AppBlogsEntriesPeer::ID, $this->id);
		if ($this->isColumnModified(AppBlogsEntriesPeer::PAGE_ID)) $criteria->add(AppBlogsEntriesPeer::PAGE_ID, $this->page_id);
		if ($this->isColumnModified(AppBlogsEntriesPeer::LANG)) $criteria->add(AppBlogsEntriesPeer::LANG, $this->lang);
		if ($this->isColumnModified(AppBlogsEntriesPeer::TITLE)) $criteria->add(AppBlogsEntriesPeer::TITLE, $this->title);
		if ($this->isColumnModified(AppBlogsEntriesPeer::SUBTITLE1)) $criteria->add(AppBlogsEntriesPeer::SUBTITLE1, $this->subtitle1);
		if ($this->isColumnModified(AppBlogsEntriesPeer::SUBTITLE2)) $criteria->add(AppBlogsEntriesPeer::SUBTITLE2, $this->subtitle2);
		if ($this->isColumnModified(AppBlogsEntriesPeer::BODY)) $criteria->add(AppBlogsEntriesPeer::BODY, $this->body);
		if ($this->isColumnModified(AppBlogsEntriesPeer::DATE)) $criteria->add(AppBlogsEntriesPeer::DATE, $this->date);
		if ($this->isColumnModified(AppBlogsEntriesPeer::TAGS)) $criteria->add(AppBlogsEntriesPeer::TAGS, $this->tags);
		if ($this->isColumnModified(AppBlogsEntriesPeer::URL)) $criteria->add(AppBlogsEntriesPeer::URL, $this->url);
		if ($this->isColumnModified(AppBlogsEntriesPeer::SITE_ID)) $criteria->add(AppBlogsEntriesPeer::SITE_ID, $this->site_id);
		if ($this->isColumnModified(AppBlogsEntriesPeer::ACTIU)) $criteria->add(AppBlogsEntriesPeer::ACTIU, $this->actiu);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(AppBlogsEntriesPeer::DATABASE_NAME);

		$criteria->add(AppBlogsEntriesPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of AppBlogsEntries (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setPageId($this->page_id);

		$copyObj->setLang($this->lang);

		$copyObj->setTitle($this->title);

		$copyObj->setSubtitle1($this->subtitle1);

		$copyObj->setSubtitle2($this->subtitle2);

		$copyObj->setBody($this->body);

		$copyObj->setDate($this->date);

		$copyObj->setTags($this->tags);

		$copyObj->setUrl($this->url);

		$copyObj->setSiteId($this->site_id);

		$copyObj->setActiu($this->actiu);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getAppBlogMultimediaEntriess() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addAppBlogMultimediaEntries($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     AppBlogsEntries Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     AppBlogsEntriesPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new AppBlogsEntriesPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a AppBlogsPages object.
	 *
	 * @param      AppBlogsPages $v
	 * @return     AppBlogsEntries The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setAppBlogsPages(AppBlogsPages $v = null)
	{
		if ($v === null) {
			$this->setPageId(NULL);
		} else {
			$this->setPageId($v->getId());
		}

		$this->aAppBlogsPages = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the AppBlogsPages object, it will not be re-added.
		if ($v !== null) {
			$v->addAppBlogsEntries($this);
		}

		return $this;
	}


	/**
	 * Get the associated AppBlogsPages object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     AppBlogsPages The associated AppBlogsPages object.
	 * @throws     PropelException
	 */
	public function getAppBlogsPages(PropelPDO $con = null)
	{
		if ($this->aAppBlogsPages === null && ($this->page_id !== null)) {
			$this->aAppBlogsPages = AppBlogsPagesPeer::retrieveByPk($this->page_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aAppBlogsPages->addAppBlogsEntriess($this);
			 */
		}
		return $this->aAppBlogsPages;
	}

	/**
	 * Clears out the collAppBlogMultimediaEntriess collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addAppBlogMultimediaEntriess()
	 */
	public function clearAppBlogMultimediaEntriess()
	{
		$this->collAppBlogMultimediaEntriess = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collAppBlogMultimediaEntriess collection (array).
	 *
	 * By default this just sets the collAppBlogMultimediaEntriess collection to an empty array (like clearcollAppBlogMultimediaEntriess());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initAppBlogMultimediaEntriess()
	{
		$this->collAppBlogMultimediaEntriess = array();
	}

	/**
	 * Gets an array of AppBlogMultimediaEntries objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this AppBlogsEntries has previously been saved, it will retrieve
	 * related AppBlogMultimediaEntriess from storage. If this AppBlogsEntries is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array AppBlogMultimediaEntries[]
	 * @throws     PropelException
	 */
	public function getAppBlogMultimediaEntriess($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AppBlogsEntriesPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAppBlogMultimediaEntriess === null) {
			if ($this->isNew()) {
			   $this->collAppBlogMultimediaEntriess = array();
			} else {

				$criteria->add(AppBlogMultimediaEntriesPeer::ENTRIES_ID, $this->id);

				AppBlogMultimediaEntriesPeer::addSelectColumns($criteria);
				$this->collAppBlogMultimediaEntriess = AppBlogMultimediaEntriesPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(AppBlogMultimediaEntriesPeer::ENTRIES_ID, $this->id);

				AppBlogMultimediaEntriesPeer::addSelectColumns($criteria);
				if (!isset($this->lastAppBlogMultimediaEntriesCriteria) || !$this->lastAppBlogMultimediaEntriesCriteria->equals($criteria)) {
					$this->collAppBlogMultimediaEntriess = AppBlogMultimediaEntriesPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastAppBlogMultimediaEntriesCriteria = $criteria;
		return $this->collAppBlogMultimediaEntriess;
	}

	/**
	 * Returns the number of related AppBlogMultimediaEntries objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related AppBlogMultimediaEntries objects.
	 * @throws     PropelException
	 */
	public function countAppBlogMultimediaEntriess(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AppBlogsEntriesPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collAppBlogMultimediaEntriess === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(AppBlogMultimediaEntriesPeer::ENTRIES_ID, $this->id);

				$count = AppBlogMultimediaEntriesPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(AppBlogMultimediaEntriesPeer::ENTRIES_ID, $this->id);

				if (!isset($this->lastAppBlogMultimediaEntriesCriteria) || !$this->lastAppBlogMultimediaEntriesCriteria->equals($criteria)) {
					$count = AppBlogMultimediaEntriesPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collAppBlogMultimediaEntriess);
				}
			} else {
				$count = count($this->collAppBlogMultimediaEntriess);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a AppBlogMultimediaEntries object to this object
	 * through the AppBlogMultimediaEntries foreign key attribute.
	 *
	 * @param      AppBlogMultimediaEntries $l AppBlogMultimediaEntries
	 * @return     void
	 * @throws     PropelException
	 */
	public function addAppBlogMultimediaEntries(AppBlogMultimediaEntries $l)
	{
		if ($this->collAppBlogMultimediaEntriess === null) {
			$this->initAppBlogMultimediaEntriess();
		}
		if (!in_array($l, $this->collAppBlogMultimediaEntriess, true)) { // only add it if the **same** object is not already associated
			array_push($this->collAppBlogMultimediaEntriess, $l);
			$l->setAppBlogsEntries($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this AppBlogsEntries is new, it will return
	 * an empty collection; or if this AppBlogsEntries has previously
	 * been saved, it will retrieve related AppBlogMultimediaEntriess from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in AppBlogsEntries.
	 */
	public function getAppBlogMultimediaEntriessJoinAppBlogsMultimedia($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AppBlogsEntriesPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAppBlogMultimediaEntriess === null) {
			if ($this->isNew()) {
				$this->collAppBlogMultimediaEntriess = array();
			} else {

				$criteria->add(AppBlogMultimediaEntriesPeer::ENTRIES_ID, $this->id);

				$this->collAppBlogMultimediaEntriess = AppBlogMultimediaEntriesPeer::doSelectJoinAppBlogsMultimedia($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(AppBlogMultimediaEntriesPeer::ENTRIES_ID, $this->id);

			if (!isset($this->lastAppBlogMultimediaEntriesCriteria) || !$this->lastAppBlogMultimediaEntriesCriteria->equals($criteria)) {
				$this->collAppBlogMultimediaEntriess = AppBlogMultimediaEntriesPeer::doSelectJoinAppBlogsMultimedia($criteria, $con, $join_behavior);
			}
		}
		$this->lastAppBlogMultimediaEntriesCriteria = $criteria;

		return $this->collAppBlogMultimediaEntriess;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collAppBlogMultimediaEntriess) {
				foreach ((array) $this->collAppBlogMultimediaEntriess as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collAppBlogMultimediaEntriess = null;
			$this->aAppBlogsPages = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseAppBlogsEntries:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseAppBlogsEntries::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseAppBlogsEntries
