<?php

require 'lib/model/om/BaseChat.php';


/**
 * Skeleton subclass for representing a row from the 'chat' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 02/15/11 11:21:03
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Chat extends BaseChat {

	/**
	 * Initializes internal state of Chat object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}

} // Chat
