<?php

require 'lib/model/om/BaseEntradesReserva.php';


/**
 * Skeleton subclass for representing a row from the 'entrades_reserva' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 04/27/11 14:57:30
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class EntradesReserva extends BaseEntradesReserva {

    public function getEstatString()
    {
        switch($this->getEstat()){
            case EntradesReservaPeer::ANULADA: return 'Anul·lada';
            case EntradesReservaPeer::CONFIRMADA: return 'Confirmada';
            case EntradesReservaPeer::ENVIADA: return 'Enviada';
        }
    }

    public function setInactiu()
    {
        $this->setActiu(false);
        $this->save();
    }

    public function getHorari(){
        $C = new Criteria();
        $C = HorarisPeer::getCriteriaActiu($C,null);
        $C->add(HorarisPeer::HORARISID,$this->getHorarisid());        
        return HorarisPeer::doSelectOne($C);
    }

} // EntradesReserva
