<?php

require 'lib/model/om/BaseMultimedia.php';


/**
 * Skeleton subclass for representing a row from the 'multimedia' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 02/15/11 11:40:28
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Multimedia extends BaseMultimedia {

    public function getLargeImage(){
        $url = $this->getUrl();
        list($nom,$ext) = explode('.',$url);
        return $nom.'-L.'.$ext;
    }

} // Multimedia
