# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: web, action: index }


#####################################################
# GESTIÓ                                            #
#####################################################

gAdmin:
  url: /gestio/main
  param: { module:gestio, action:main  }
  
gUser:
  url: /gestio/uGestio
  param: { module:gestio, action:uGestio  }
  
uLogin:
  url: /gestio/uLogin
  param: { module:gestio, action:uLogin  }

#####################################################
# FACEBOOK                                          #
#####################################################
  
gConfig:
  url: /gestio/gConfig
  param: { module:gestio, action:gConfig }

fb_login:
  url: /gestio/fb_login
  param: { module:gestio, action:uLogin, accio:FB_LOGIN }

fb_link:
  url: /gestio/fb_link
  param: { module:gestio, action:gConfig, accio:FB_LINK }
  
fb_unlink:
  url: /gestio/fb_unlink
  param: { module:gestio, action:gConfig, accio:FB_UNLINK }  
  
fb_user_link:
  url: /gestio/fb_user_link
  param: { module:gestio, action:uGestio, accio:FB_LINK }
  
fb_user_unlink:
  url: /gestio/fb_user_unlink
  param: { module:gestio, action:uGestio, accio:FB_UNLINK }  

#####################################################
# NOTICIES CULTURALS                                #
#####################################################

noticies_culturals:
  url:  /noticiesculturals
  param: { module:blogs, action:noticiesculturals }


#####################################################
# WEB CCG                                           #
#####################################################

web_contingut_auto:
  url: /web/cicles/:node/:titol
  param: { module:web, action:index, accio:ac }

web_contingut_man:
  url: /web/contingut/:node/:titol
  param: { module:web, action:index, accio:mc }
  
web_noticia:
  url: /web/noticies/:idN/:p/:titol
  param: { module:web, action:index }

web_activitat:
  url: /web/activitat/:idA/:titol
  param: { module:web, action:index, accio:caa }

web_cicle:
  url: /web/cicle/:idC/:titol
  param: { module:web, action:index, accio:cc  }

#####################################################
# BACKGROUND                                        #
#####################################################

reserva_espai_remember_mail:
  url: /gestio/background/reserva_remember
  param: { module: gestio, action:sBackground, accio:RECORDATORI_RESERVA_ESPAIS }

#####################################################
# GENERIQUES                                        #
# please, remove them by adding more specific rules #
#####################################################

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*